# Ticat-deploy.yml

name: Ticat-deploy to Amazon EC2

on:
  push:
    branches: [dev]
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script_stop: true
          script: |
              lsof -i :8080
              fuser -k -n tcp 8080
              
              
#       - name: Grant execute permission for gradlew
#         run: chmod +x ./gradlew
#         shell: bash

#       - name: Git pull
#         run: |
#          cd $HOME
#          cd Ticat-server
#          git pull origin main
      
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
            arguments: build
              
      - name: Run JAR File
        run: |
          cd libs
          java -jar Ticat-0.0.1-SNAPSHOT.jar
        shell: bash  
